package com.google.calendar.test;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import com.google.calendar.googlecalendar.Library;

public class LibraryTest {
    /*@Test public void testSomeLibraryMethod()*/ {
        Library classUnderTest = new Library();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
